name             'java-windows'
maintainer       'jay flowers'
maintainer_email 'jay.flowers@gmail.com'
license          'All rights reserved'
description      'Installs/Configures java'
long_description 'Installs/Configures java'
version          '1.0.0'

supports 'windows'
depends 'windows'
